# Generated by Django 3.2.8 on 2022-08-08 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20220808_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='student',
            new_name='students',
        ),
    ]
