# Generated by Django 3.2.8 on 2022-08-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20220805_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='release_date',
        ),
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.FloatField(),
        ),
    ]
